package org.sunnycake.aton.dto;
// Generated 28/01/2016 05:23:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EstadoId generated by hbm2java
 */
public class EstadoPK  implements java.io.Serializable {


     private String equipo;
     private Date fecha;

    public EstadoPK() {
    }

    public EstadoPK(String equipo, Date fecha) {
       this.equipo = equipo;
       this.fecha = fecha;
    }
   
    public String getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(String equipo) {
        this.equipo = equipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstadoPK) ) return false;
		 EstadoPK castOther = ( EstadoPK ) other; 
         
		 return ( (this.getEquipo()==castOther.getEquipo()) || ( this.getEquipo()!=null && castOther.getEquipo()!=null && this.getEquipo().equals(castOther.getEquipo()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEquipo() == null ? 0 : this.getEquipo().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


