package org.sunnycake.aton.dto;
// Generated 28/01/2016 05:23:03 PM by Hibernate Tools 4.3.1



/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private EstadoPK id;
     private Equipo equipo;
     private String descripcion;

    public Estado() {
    }

	
    public Estado(EstadoPK id, Equipo equipo) {
        this.id = id;
        this.equipo = equipo;
    }
    public Estado(EstadoPK id, Equipo equipo, String descripcion) {
       this.id = id;
       this.equipo = equipo;
       this.descripcion = descripcion;
    }
   
    public EstadoPK getId() {
        return this.id;
    }
    
    public void setId(EstadoPK id) {
        this.id = id;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


