package org.sunnycake.aton.dto;
// Generated 28/01/2016 05:23:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrdenId generated by hbm2java
 */
public class OrdenPK  implements java.io.Serializable {


     private String eqSesion;
     private Date fecha;

    public OrdenPK() {
    }

    public OrdenPK(String eqSesion, Date fecha) {
       this.eqSesion = eqSesion;
       this.fecha = fecha;
    }
   
    public String getEqSesion() {
        return this.eqSesion;
    }
    
    public void setEqSesion(String eqSesion) {
        this.eqSesion = eqSesion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdenPK) ) return false;
		 OrdenPK castOther = ( OrdenPK ) other; 
         
		 return ( (this.getEqSesion()==castOther.getEqSesion()) || ( this.getEqSesion()!=null && castOther.getEqSesion()!=null && this.getEqSesion().equals(castOther.getEqSesion()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEqSesion() == null ? 0 : this.getEqSesion().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


