package org.sunnycake.aton.dto;
// Generated 28/01/2016 05:23:03 PM by Hibernate Tools 4.3.1



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int id;
     private UsuarioWeb usuarioweb;
     private String rol;

    public Rol() {
    }

	
    public Rol(int id, UsuarioWeb usuarioweb) {
        this.id = id;
        this.usuarioweb = usuarioweb;
    }
    public Rol(int id, UsuarioWeb usuarioweb, String rol) {
       this.id = id;
       this.usuarioweb = usuarioweb;
       this.rol = rol;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public UsuarioWeb getUsuarioweb() {
        return this.usuarioweb;
    }
    
    public void setUsuarioweb(UsuarioWeb usuarioweb) {
        this.usuarioweb = usuarioweb;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }




}


