package org.sunnycake.aton.dto;
// Generated 28/01/2016 05:23:03 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Sala generated by hbm2java
 */
@XmlRootElement 
public class Sala implements java.io.Serializable {

    private int id;
    private Laboratorio laboratorio;
    private String nombre;
    private String mediosaudiovisuales;
    private String enseres;
    private Set equipos = new HashSet(0);

    public Sala() {
    }

    public Sala(int id) {
        this.id = id;
    }

    public Sala(int id, Laboratorio laboratorio, String nombre, String mediosaudiovisuales, String enseres, Set equipos) {
        this.id = id;
        this.laboratorio = laboratorio;
        this.nombre = nombre;
        this.mediosaudiovisuales = mediosaudiovisuales;
        this.enseres = enseres;
        this.equipos = equipos;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Laboratorio getLaboratorio() {
        return this.laboratorio;
    }

    public void setLaboratorio(Laboratorio laboratorio) {
        this.laboratorio = laboratorio;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getMediosaudiovisuales() {
        return this.mediosaudiovisuales;
    }

    public void setMediosaudiovisuales(String mediosaudiovisuales) {
        this.mediosaudiovisuales = mediosaudiovisuales;
    }

    public String getEnseres() {
        return this.enseres;
    }

    public void setEnseres(String enseres) {
        this.enseres = enseres;
    }

    public Set<Equipo> getEquipos() {
        return this.equipos;
    }

    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }

    public Sala(int id, String nombre, Laboratorio laboratorio, String mediosAudiovisuales, String enseres) {
        this.id = id;
        this.nombre = nombre;
        this.laboratorio = laboratorio;
        this.mediosaudiovisuales = mediosAudiovisuales;
        this.enseres = enseres;
    }

}
