package org.sunnycake.aton.dto;
// Generated 28/01/2016 05:23:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private SesionPK id;
     private Equipo equipo;
     private String sistemaoperativo;
     private String usuario;
     private Boolean activa;
     private Set sugerencias = new HashSet(0);

    public Sesion() {
    }

	
    public Sesion(SesionPK id, Equipo equipo) {
        this.id = id;
        this.equipo = equipo;
    }
    public Sesion(SesionPK id, Equipo equipo, String sistemaoperativo, String usuario, Boolean activa, Set sugerencias) {
       this.id = id;
       this.equipo = equipo;
       this.sistemaoperativo = sistemaoperativo;
       this.usuario = usuario;
       this.activa = activa;
       this.sugerencias = sugerencias;
    }
   
    public SesionPK getId() {
        return this.id;
    }
    
    public void setId(SesionPK id) {
        this.id = id;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getSistemaoperativo() {
        return this.sistemaoperativo;
    }
    
    public void setSistemaoperativo(String sistemaoperativo) {
        this.sistemaoperativo = sistemaoperativo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Boolean getActiva() {
        return this.activa;
    }
    
    public void setActiva(Boolean activa) {
        this.activa = activa;
    }
    public Set getSugerencias() {
        return this.sugerencias;
    }
    
    public void setSugerencias(Set sugerencias) {
        this.sugerencias = sugerencias;
    }




}


