package org.sunnycake.aton.dto;
// Generated 28/01/2016 05:23:03 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarioweb generated by hbm2java
 */
public class UsuarioWeb implements java.io.Serializable {

    private String usuario;
    private String password;
    private Boolean enabled;
    private Set rols = new HashSet(0);
    private Set ordens = new HashSet(0);

    public UsuarioWeb() {
    }

    public UsuarioWeb(String usuario) {
        this.usuario = usuario;
    }

    public UsuarioWeb(String usuario, String password, Boolean enabled, Set rols, Set ordens) {
        this.usuario = usuario;
        this.password = password;
        this.enabled = enabled;
        this.rols = rols;
        this.ordens = ordens;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Set getRols() {
        return this.rols;
    }

    public void setRols(Set rols) {
        this.rols = rols;
    }

    public Set getOrdens() {
        return this.ordens;
    }

    public void setOrdens(Set ordens) {
        this.ordens = ordens;
    }

    public UsuarioWeb(String usuario, String password, boolean enabled) {
        this.usuario = usuario;
        this.password = password;
        this.enabled = enabled;
    }

}
